.check_data_if(check_data_if)
.check_data_id(check_data_id)
.check_data_ex(check_data_ex)
.check_data_mem(check_data_mem)
.check_data_wb(check_data_wb)
.check_data_hzd(check_data_hzd)
.check_addr(check_addr)
.check_data(check_data)